//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int EMPLOYEE_ID { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public string JOB_ID { get; set; }
        public Nullable<int> DEPARTMENT_ID { get; set; }
    }
}
