//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAMEN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ep
    {
        [DisplayName("Fecha↓")]
        public string Fecha { get; set; }
        [DisplayName("DAY↓")]
        public Nullable<int> Dia { get; set; }
        [DisplayName("meses↓")]
        public Nullable<int> Mes { get; set; }
        [DisplayName("Vendedor ID↓")]
        public int Codigo_ver { get; set; }
        [DisplayName("Name Vendedor↓")]
        public string Vendedor { get; set; }
        [DisplayName("Producto ID↓")]
        public Nullable<int> Producto { get; set; }
        [DisplayName("Producto↓")]
        public string Nombre_Produc { get; set; }
        [DisplayName("Numero de linea↓")]
        public Nullable<int> Linea { get; set; }
        [DisplayName("Nombre de linea↓")]
        public string Nombre_Linea { get; set; }
        [DisplayName("CLIENTE↓")]
        public string Cliente { get; set; }
        [DisplayName("PRECIO↓")]
        public string Precio { get; set; }
        [DisplayName("CANTIDAD↓")]
        public Nullable<int> cantidad { get; set; }
        
      
    }
}
